@startuml

class Contribuinte{
    - nome: String
    - morada: String
    - outrosRendimentos: double
    - NOME_POR_OMISSAO: String{static}
    - MORADA_POR_OMISSAO: String{static}
    - OUTROS_RENDIMENTOS_POR_OMISSAO: double{static}
    + Contribuinte(nome: String, morada: String, outrosRendimentos: double)
    + Contribuinte()
    + getNome(): String
    + getMorada(): String
    + getOutrosRendimentos(): double
    + setNome(nome: String: void
    + setMorada(morada: String): void
    + setOutrosRendimentos(outrosRendimentos: double): void
    + toString(): String
    +{abstract} calcularImposto(): double
}

class abstract

class Reformado{
    - taxaSobreRT: double{static}
    - taxaSobreOR: double{static}
    + setTaxaSobreRT(double taxaSobreRT): void
    + setTaxaSobreOR(double taxaSobreOR)): void
    + getTaxaSobreRT(): double
    + getTaxaSobreOR(): double
    + toString(): String
    + calcularImposto(): double
    + calcularImposto(): double
}


@enduml