@startuml

class main{
    + main(args : String) : void
}
abstract class Contribuinte{
    - nome: String
    - morada: String
    - {static} NOME_POR_OMISSAO: String {readOnly}
    - {static} MORADA_POR_OMISSAO: String {readOnly}
    + Contribuinte(nome: String, morada: String)
    + Contribuinte()
    + getNome(): String
    + getMorada(): String
    + setNome(nome: String: void
    + setMorada(morada: String): void
    + toString(): String
    +{abstract} calcularImposto(): double
}

 abstract class ContriuinteComRendimentosTrabalho extends Contribuinte{
    - rendimentosTrabalho: double
    - outrosRendimentos: double
    - {static} RENDIMENTOS_TRABALHO_POR_OMISSAO: double {readOnly}
    - {static} OUTROS_RENDIMENTOS_POR_OMISSAO: double {readOnly}
    + ContriuinteComRendimentosTrabalho()
    + ContriuinteComRendimentosTrabalho(nome: String, morada: String, rendimentosTrabalho: double, outrosRendimentos: double)
    + getRendimentosTrabalho(): double
    + getOutrosRendimentos(): double
    + setRendimentosTrabalho(rendimentosTrabalho: double): void
    + setOutrosRendimentos(outrosRendimentos: double): void
    + {abstract} getTaxaRendimentosTrabalho(): double
    + {abstract} getTaxaOutrosRendimentos(): double
    + calcularImposto(): double
}

class Reformado extends ContriuinteComRendimentosTrabalho{
    - taxaRendimentosTrabalho: double
    - taxaOutrosRendimentos: double
    + Reformado(nome: String, morada: String, rendimentosTrabalho: double, outrosRendimentos: double)
    + Reformado()
    + getTaxaRendimentosTrabalho(): double
    + getTaxaOutrosRendimentos(): double
    + setTaxaRendimentosTrabalho(taxaRendimentosTrabalho: double): void
    + setTaxaOutrosRendimentos(outrosRendimentos: double): void
    + toString: String
}

class Desempregado extends Contribuinte{
    - outrosRendimentos : double
    - mesesParagem : int
    - {static} taxaOutrosRendimentos : double
    - {static} OUTROS_RENDIMENTOS_POR_OMISSAO : double {readOnly}
    - {static} MESES_PARAGEM_POR_OMISSAO : double {readOnly}
    + Desempregado()
    + Desempregado(nome : String, morada : String, outrosRendimentos : double, mesesParagem : int)
    + getOutrosRendimentos() : double
    + getMesesParagem() : int
    + setOutrosRendimentos(outrosRendimentos : double) : void
    + setMesesParagem(mesesParagem : void) : void
    + setTaxaOutrosRendimentos(taxaRendimentosTrabalho : double) : void
    + toString() : String
    + calcularImposto() : double
}

class TrabalhadorContaOutrem extends ContriuinteComRendimentosTrabalho{
    - nomeEmpresa : String
    - {static} NOME_EMPRESA_POR_OMISSAO : String {readOnly}
    - {static} taxaRendimentosTrabalhoNivel1 : double
    - {static} taxaRendimentosTrabalhoNivel2 : double
    - {static} taxaOutrosRendimentos : double
    - {static} LIMITE_RENDIMENTOS_TRANALHO : double {readOnly}
    + TrabalhadorContaOutrem()
    + TrabalhadorContaOutrem(nome : String, morada : String, rendimentosTrabalho : double, outrosRendimentos : double, nomeEmpresa : String)
    + getTaxaRendimentosTrabalho() : double
    + getTaxaOutrosRendimentos() : double
    + setTaxaRendimentosTrabalhoNivel1(taxaRendimentosTrabalhoNivel1 : double) : void
    + setTaxaRendimentosTrabalhoNivel2(taxaRendimentosTrabalhoNivel2 : double) : void
    + toString() : String
}

class TrabalhadorContaPropria extends ContriuinteComRendimentosTrabalho{
    - profissao : String
    - {static} PRODISSAO_POR_OMISSAO : String {readOnly}
    - {static} taxaRendimentosTrabalho : double
    - {static} taxaRendimentosTrabalhoNivel1 : double
    - {static} taxaRendimentosTrabalhoNivel2 : double
    - {static} LIMITE_RENDIMENTOS_TRANALHO : double {readOnly}
    - {static} LIMITE_RENDIMENTOS_TRANALHO : double {readOnly}
    + TrabalhadorContaPropria(nome : String, morada : String, rendimentosTrabalho : double, outrosRendimentos : double, profissao : String)
    + TrabalhadorContaPropria()
    + getTaxaRendimentosTrabalho() : double
    + getTaxaOutrosRendimentos() : double
    + setTaxaRendimentosTrabalho(taxaRendimentosTrabalho :  double) : void
    + setTaxaOutrosRendimentosNivel1(taxaOutrosRendimentos1 : double) : void
    + setTaxaOutrosRendimentosNivel2(taxaOutrosRendimentos2 : double) : void
    + toString() : String
}

@enduml